version: "3"
services:
  database:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpachato
    ports:
      - 3306:3306
      #MYSQL_USER: tpachat_user
      #MYSQL_PASSWORD: nour
    #volumes:
      #- mysql_database:/var/lib/mysql
  spring-boot:
    depends_on:
      - database
    image: nourhenekheriji/springback
    restart: always
    ports:
      - 8089:8089
    container_name: spring
  angular:
    depends_on:
      - spring-boot
    image: nourhenekheriji/angular
    restart: always
    ports:
      - 80:80
    container_name: angular



